SELECT fi.ID AS ID,
    fni.FISH_NAME AS FISH_NAME, 
    fi.LENGTH AS LENGTH
FROM FISH_INFO fi
JOIN FISH_NAME_INFO fni
ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = fi.FISH_TYPE
)
ORDER BY ID ASC